# Generated by Django 3.1.1 on 2020-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
