# Generated by Django 3.1.1 on 2020-10-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201005_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='horario',
            field=models.TimeField(),
        ),
    ]
