# Generated by Django 3.1.1 on 2020-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201005_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
